---
# tasks file for ohs

- name: "Check OHS installation"
  stat:
    path: "/etc/init.d/{{ ohs_service }}"
  register: installation

- debug:
    msg: "{{ swapfile_count }}"

- debug: msg="{{ item.mount }}"
  loop:
    - "{{ ansible_mounts }}"

- name: "Install required packages"
  package:
    name: "{{ required_packages }}"
    state: present
  register: package_install
  until: package_install is succeeded
  become: True
  when: not installation.stat.exists

- include_tasks: "ohs.yml"
  when: not installation.stat.exists
