---

- name: "Unmount swap"
  mount:
    name: swap
    src: "{{ swapfile_path }}"
    fstype: swap
    state: unmounted
  when: swapfile.stat.exists
  tags:
    - configure_swapfile
    - configure_system
    - prepare_for_install

- name: "Create swapfile"
  command: "dd if=/dev/zero of={{ swapfile_path }} bs={{ swapfile_bs_size_mb }}M
            count={{ swapfile_count }} creates={{ swapfile_path }}"
  become: True
  when: not swapfile.stat.exists
  tags:
    - configure_swapfile
    - configure_system
    - prepare_for_install

- name: "Set swapfile permissions"
  file:
    path: "{{ swapfile_path }}"
    mode: 0600
  become: True
  tags:
    - configure_swapfile
    - configure_system
    - prepare_for_install

- name: "Mmake swap"
  command: "/sbin/mkswap {{ swapfile_path }}"
  become: True
  when: not swapfile.stat.exists
  tags:
    - configure_swapfile
    - configure_system
    - prepare_for_install

- name: "Swap on"
  command: "/sbin/swapon {{ swapfile_path }}"
  become: True
  when: not swapfile.stat.exists
  tags:
    - configure_swapfile
    - configure_system
    - prepare_for_install

- name: "Add swap to /etc/fstab"
  lineinfile:
    dest: /etc/fstab
    line: "{{ swapfile_path }} swap swap 0 0"
    state: present
  become: True
  when: not swapfile.stat.exists
  tags:
    - configure_swapfile
    - configure_system
    - prepare_for_install
