---
- name: "Check swapfile"
  stat:
    path: "{{ swapfile_path }}"
  register: swapfile
  tags:
    - configure_swapfile
    - configure_system
    - prepare_for_install

- name: "Unmount swap"
  mount:
    name: swap
    src: "{{ swapfile_path }}"
    fstype: swap
    state: unmounted
  when: swapfile.stat.exists
  tags:
    - configure_swapfile
    - configure_system
    - prepare_for_install

- name: "Set swapfile permissions"
  file:
    path: "{{ swapfile_path }}"
    mode: 0644
  become: True
  when: swapfile.stat.exists
  tags:
    - configure_swapfile
    - configure_system
    - prepare_for_install

- name: "Swap off"
  command: "/sbin/swapoff {{ swapfile_path }}"
  become: True
  when: swapfile.stat.exists
  tags:
    - configure_swapfile
    - configure_system
    - prepare_for_install

- name: "Remove swap from /etc/fstab"
  lineinfile:
    dest: /etc/fstab
    regexp: "^{{ swapfile_path }} swap swap 0 0"
    state: absent
  become: True
  when: swapfile.stat.exists
  tags:
    - configure_swapfile
    - configure_system
    - prepare_for_install
  ignore_errors: True

- name: "Remove swap file"
  file:
    path: "{{ swapfile_path }}"
    state: absent
  when: swapfile.stat.exists
  ignore_errors: True
