---
- name: Prepare Ubuntu / Debian
  hosts: debian_family
  gather_facts: False
  tasks:
    - name: Workaround for Ubuntu/Debian images
      raw: |
        apt-get update
      become: True
      changed_when: False

    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt install -y python-minimal python-zipstream)
      become: True
      changed_when: False
      register: update_result
      retries: 10
      delay: 5
      until: update_result.rc == 0

- name: Prepare RHEL
  hosts: rhel_family
  gather_facts: False
  tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (yum install -y python2 python-simplejson)
      become: True
      changed_when: False
      register: update_result
      retries: 10
      delay: 5
      until: update_result.rc == 0

    # - name: Expand volume
    #   shell: resize2fs /dev/sda1
    #   become: True

    - name: Debug volume
      shell: df -h
      become: True
