#!/bin/bash
sudo yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm cloud-utils cloud-utils-growpart
sudo yum -y install cloud-utils cloud-utils-growpart
sudo growpart /dev/xvda 1
sudo resize2fs /dev/xvda1
sudo reboot
