---
- name: Prepare RHEL
  hosts: rhel_family
  gather_facts: False
  tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (yum install -y python2 python-simplejson)
      become: True
      changed_when: False

    - name: Workaround for AWS facts
      ec2_metadata_facts:
      ignore_errors: yes

    - name: Gather facts
      setup:

    - block:
      - name: Install modules
        package:
          name: "{{ item }}"
          state: present
        loop:
          - epel-release
          - cloud-init
          - dracut-modules-growroot

      - name: Rebuild all initramfs images
        shell: rpm -qa kernel | sed 's/^kernel-//' | xargs -I {} dracut -f /boot/initramfs-{}.img {}
        args:
          warn: False
        register: extend_partition

      - block:
        - name: Restart server
          shell: sleep 2 && shutdown -r now "Ansible restart"

        - name: Wait for server to restart
          wait_for_connection:
            delay: 10
            timeout: 360

        - name: Wait for the server to finish rebooting
          wait_for:
            host: "{{ public_hostname }}"
            search_regex: SSH
            port: 22
            timeout: 320
          vars:
            public_hostname: "{{ ansible_ec2_public_hostname }}"
        when: extend_partition is changed
      become: True
      when:
        - ansible_distribution_major_version == '6'
        - ansible_ec2_instance_type is defined
